version: 2
jobs:
  build:
    docker:
      - image: circleci/android:api-26-alpha
    working_directory: ~/bigbang
    environment:
      JVM_OPTS: -Xmx3200m
    #    resource_class: large
    steps:
      - checkout
      - restore_cache:
          key: jars-{{ checksum "build.gradle" }}-{{ checksum  "app/build.gradle" }}
      - run:
          name: Download Dependencies
          command: ./gradlew androidDependencies
      - save_cache:
          paths:
            - ~/.gradle
          key: jars-{{ checksum "build.gradle" }}-{{ checksum  "app/build.gradle" }}
      - run:
          name: Build
          command: ./gradlew clean install
            --no-daemon -Pkotlin.incremental=false --max-workers=2
      - run:
          name: Assemble modules
          command: ./gradlew :core:assembleDebug
            :dbflow:assembleDebug
            :instrumental-test:assembleDebug
            :log-crashlytics:assembleDebug
            :mvp:assembleDebug
            :mvvm:assembleDebug
            :retrofit:assembleDebug
            :ui:assembleDebug
            --max-workers=2
      - run:
          name: Assemble instrumental tests
          command: ./gradlew assembleAndroidTest
            --max-workers=2
      - run:
          name: Run Tests
          command: ./gradlew test
            lint
            --max-workers=2
      - run:
          name: Compile App Module
          command: ./gradlew :app:compileLollipopAndAboveProductionReleaseSources --max-workers=1
      - store_artifacts:
          path: app/build/reports
          destination: reports
      - store_test_results:
          path: app/build/test-results
